### PR TITLE
update virtualenv and readme

### PR DESCRIPTION
**Pull request by czue**
good to go

### CODE REVIEW

**Comment by czue** [comment]
can merge when https://github.com/dimagi/commcare-hq/pull/7540 passes

**Comment by czue** [comment]
@snopoke @dannyroberts probably worth just double checking the readme changes but I think this is good to go :white_check_mark:

**Comment by czue** [comment]
seems to speed up the build by about a minute. and (more importantly to me) I'm pretty sure this is going to fix that intermittent ownership cleanliness test failure I couldn't get to the bottom of.

**Comment by snopoke** [comment]
LGTM

**Comment by dannyroberts** [comment]
Nice! Been a while since we updated that!

**Pull request merged**
